### PR TITLE
Addition of Performance Insights for older Terarform AWS RDS Module

### PR DESCRIPTION
**Pull request by triwats**
##### Corresponding Issue(s):
- NA

##### Summary of change(s):
* Adding Performance Insights variable for the older flavour of the RDS Metrics with the resource attribute defined here [available here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#performance_insights_enabled).

##### Reason for Change(s):

* Impossible currently to enable Performance Insights within the older module version with Terraform related to 0.0.11 syntax, I'd suggest we tag it as `0.0.15` in this case!

##### Will the change trigger resource destruction or replacement? If yes, please provide justification:

* Will make a resource change to allow the Performance Insights in AWS  [1]

##### Does this update/change involve issues with other external modules? If so, please describe the scenario.
* Would pull in new version of the module for customers where the version is explicitly changed

```hcl
module "rds" {
source = "git@github.com:rackspace-infrastructure-automation/aws-terraform-rds//?ref=v0.0.14"
...
}
```

##### If input variables or output variables have changed or has been added, have you updated the README?

Yes!

##### Do examples need to be updated based on changes?

Not strictly necessary

##### Note to the PR requester about Closing PR's
Please message the person that opened the issue when auto closing it on slack, as well as any other stake holders of deep interest. Only close the issue if you believe that the issue is fully resolved with this PR.

#### This PR may auto close the issue associated with it. If you feel the issue is not resolved please reopen the issue.

[1] https://aws.amazon.com/rds/performance-insights/

### CODE REVIEW

**Comment by triwats** [comment]
Note: I _think_ I need to change this to include the options for the other two attributes:

[performance_insights_kms_key_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#performance_insights_kms_key_id)

[performance_insights_retention_period](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#performance_insights_retention_period)

**Review by OscarB89 — APPROVED** [review]

**Comment by gdelvalle** [comment]
Hi Folks, @triwats , 
Generally we've taken the stance to only backport bug fixes into the 0.11 branches of these modules, but given that you guys have taken some time and effort we'll look at this to be included.  That said, we wont be able to have a look and do the necessary for a week or 2.  If you guys are happy with your change as it exists now, I'd recommend you fork our repo into your account repo and consume your updated module from there.  Once we've addressed the changes on our end, and assuming no breaking changes between your version and ours, you can then just cut  back over to  the release we publish.

**Comment by triwats** [comment]
Hi there @gdelvalle - thanks for getting back to me!

I understand the approach here, we could use the fork as the Terraform module source, but we're in a bit of an odd situation where in one Terraform environment the module is included in project, and the production one is referencing this module instead. 

Not sure what would happen if I changed the module source, but assuming that it would want to re-create the resources instead of managing them sanely. I am keen to help here if it's useful, I believe the other above two resources would need defining for this to work. I can make that addition.

Great profile photo by the way.

**Comment by gdelvalle** [comment]
Hi @triwats , changing module source doesn't cause a  resource rebuild ( all other things being equal).  Last time i tried it anyway, but worth verifying.  I think it would cause replacement if our changes required that (changing engines or something of  that nature).
If you can wait, i'll have a look at this by tomorrow, the latest.

**Comment by gdelvalle** [comment]
@triwats , just now looking.  Per your earlier comment, we would indeed need the other 2 parameters.  Have you updated your solution to include these parameters?

[performance_insights_kms_key_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#performance_insights_kms_key_id)

[performance_insights_retention_period](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#performance_insights_retention_period)

**Comment by triwats** [comment]
Closing - as this solution is to my knowledge now deprecated.

**Pull request closed without merging**
