### PR TITLE
Remove data lookup for R53 zone ID and variable all R53 info

### PR DESCRIPTION
**Pull request by dannyleesmith**
##### Corresponding Issue(s) or trello card(s):
None
##### Summary of change(s):
Remove data object for Route 53 lookup as there were potential issues with it:
- v0.0.7 changes saw it as something to plan every time
- v0.0.6 had issues if a destruction failed and the intended zone was removed, the next destruction would fail
- potential conflicts in use cases where multiple of the same zone name may exist in an environment
##### Will the change trigger resource destruction or replacement? If yes, please provide justification:
No
##### Does this update/change involve issues with other external modules? If so, please describe the scenario.
No
##### If input variables or output variables have changed or has been added, have you updated the README?
Yes
##### Do examples need to be updated based on changes?
No
##### Note to the PR requester about Closing PR's
Please message the person that opened the issue when auto closing it on slack, as well as any other stake holders of deep interest. Only close the issue if you believe that the issue is fully resolved with this PR.

#### This PR may auto close the issue associated with it. If you feel the issue is not resolved please reopen the issue.

### CODE REVIEW

**Comment by njgarratt** [comment]
i agree that removing this altogether is the more elegant solution. it's redundant since the zone_id is already known in the caller. i only reluctantly used the explicit dependencies and that does cause annoying side effects.

i've tested this this in my use case and so far appears to work as expected. another destroy/create cycle to go and i'll be happy.

**Comment by johnctitus** [comment]
> i agree that removing this altogether is the more elegant solution. it's redundant since the zone_id is already known in the caller.

I disagree.  Asking for information that can be looked up is not the more elegant solution.  The route53 internal zone would not always be created in the same layer as the RDS instance, so the zone_id is not necessarily known in the caller.  Which lookup key can be debated, but regardless asking for something we can easily lookup should be discouraged.

The important fact is this data resource either has issues after deleting or recreates every plan\apply due to bugs in Terraform processing.  This behavior warrants removal of the resource.  The resource recreation behavior does not occur when the data resource dependency is implicit, but does when it is explicit, means this is truly a bug that should be filed on the AWS Terraform provider.

**Comment by njgarratt** [comment]
i would tend to err on the side of simplicity, but i am likely blinkered by the context in which i would tend to us this module. you have certainly seen more variations in it's use.

if we can raise a bug and get this resolved without removing functionality, then all the better. the behaviour we are seeing certainly  *should* not be happening. let me know how i can help here.

i was considering adding a lifecycle block to work around this annoyance, but that felt like digging myself deeper into a hole and then @dannyleesmith submitted his PR which made it all go away in all senses :)

**Comment by johnctitus** [comment]
For the short term, I am in 100% agreement, we should proceed with this change and remove the resource.  There is not any sense in blocking current use of the module if\while a fix to the bug is being worked on.

Once the issue has been resolved, we can look at adding the data resource back in.

**Comment by dannyleesmith** [comment]
@johnctitus thanks very much, can I get a v0.0.8 please?

**Comment by dannyleesmith** [comment]
@johnctitus my bad, shall I pull my tag down?

**Comment by njgarratt** [comment]
i just rebased, so once CI is done we should be good to go

**Pull request merged**
